/* Auto-generated ASI patch: ForceBumpTerrain  (x64) */
/* Force high-quality bump terrain at all zoom levels by NOPing the call that enables baked (low-quality) terrain during zoom-out. Targets TerrainCameraState_Update -> SetUseBakedTerrain(1). */
/* Generated by retools/asi_patcher.py */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#pragma comment(lib, "kernel32.lib")
int _fltused = 0;

static UINT_PTR g_base;

static UINT_PTR rva(UINT_PTR offset)
{
    return g_base + offset;
}

static void write_mem(volatile unsigned char *dst,
                      const unsigned char *src, unsigned int len)
{
    unsigned int i;
    for (i = 0; i < len; i++) dst[i] = src[i];
}

static void fill_nop(volatile unsigned char *dst, unsigned int len)
{
    unsigned int i;
    for (i = 0; i < len; i++) dst[i] = 0x90;
}

static int patch_bytes(UINT_PTR addr, const unsigned char *data,
                       unsigned int len)
{
    DWORD old;
    if (!VirtualProtect((void *)addr, len, PAGE_EXECUTE_READWRITE, &old))
        return 0;
    write_mem((unsigned char *)addr, data, len);
    VirtualProtect((void *)addr, len, old, &old);
    return 1;
}

static int patch_nop(UINT_PTR addr, unsigned int len)
{
    DWORD old;
    if (!VirtualProtect((void *)addr, len, PAGE_EXECUTE_READWRITE, &old))
        return 0;
    fill_nop((unsigned char *)addr, len);
    VirtualProtect((void *)addr, len, old, &old);
    return 1;
}

static HANDLE g_log = INVALID_HANDLE_VALUE;

static void log_open(void)
{
    char path[MAX_PATH];
    GetModuleFileNameA(NULL, path, MAX_PATH);
    {
        char *slash = path, *p = path;
        while (*p) { if (*p == '\\' || *p == '/') slash = p; p++; }
        slash[1] = '\0';
    }
    {
        const char nm[] = "ForceBumpTerrain.log";
        char *dst = path;
        const char *src;
        while (*dst) dst++;
        src = nm;
        while (*src) *dst++ = *src++;
        *dst = '\0';
    }
    g_log = CreateFileA(path, GENERIC_WRITE, FILE_SHARE_READ, NULL,
                        CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
}

static void log_str(const char *s)
{
    DWORD n;
    const char *p;
    if (g_log == INVALID_HANDLE_VALUE) return;
    p = s;
    while (*p) p++;
    WriteFile(g_log, s, (DWORD)(p - s), &n, NULL);
}

static void log_hex(UINT_PTR v)
{
    char buf[19];
    const char hex[] = "0123456789ABCDEF";
    int i;
    buf[0] = '0'; buf[1] = 'x';
    for (i = 0; i < 16; i++)
        buf[2 + i] = hex[(v >> (60 - i * 4)) & 0xF];
    buf[18] = '\0';
    log_str(buf);
}

static void log_patch(const char *name, UINT_PTR addr, int ok)
{
    log_str(ok ? "[OK]   " : "[FAIL] ");
    log_str(name);
    log_str(" @ ");
    log_hex(addr);
    log_str("\r\n");
}

static void log_flush(void)
{
    if (g_log != INVALID_HANDLE_VALUE) FlushFileBuffers(g_log);
}

static void log_close(void)
{
    if (g_log != INVALID_HANDLE_VALUE) CloseHandle(g_log);
    g_log = INVALID_HANDLE_VALUE;
}

static int verify_exe(void)
{
    {
        const unsigned char expect[] = { 0xE8, 0xF9, 0x80, 0xE6, 0xFF };
        if (IsBadReadPtr((void *)rva(0x00000000002CF7D2), 5))
            return 0;
        {
            const unsigned char *p = (const unsigned char *)rva(0x00000000002CF7D2);
            unsigned int i;
            for (i = 0; i < 5; i++)
                if (p[i] != expect[i]) return 0;
        }
    }
    return 1;
}

static int apply_NopSetBakedTerrainCall(void)
{
    return patch_nop(rva(0x00000000002CF7D2), 5);
}

BOOL APIENTRY DllMain(HMODULE hModule, DWORD reason, LPVOID lpReserved)
{
    (void)lpReserved;
    if (reason != DLL_PROCESS_ATTACH)
        return TRUE;
    DisableThreadLibraryCalls(hModule);
    g_base = (UINT_PTR)GetModuleHandleA(NULL);
    log_open();
    log_str("ForceBumpTerrain loaded\r\n");
    log_str("Base: "); log_hex(g_base); log_str("\r\n");

    if (!verify_exe()) {
        log_str("verify FAILED -- wrong binary?\r\n");
        log_close();
        return TRUE;
    }
    log_str("verify OK\r\n");

    log_patch("NopSetBakedTerrainCall", rva(0x00000000002CF7D2), apply_NopSetBakedTerrainCall());

    log_str("All patches applied\r\n");
    log_flush();
    return TRUE;
}
